sudo: required

language: go

go:
  - "1.13.x"

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - docker build -t mbialon/concourse-docker-manifest-resource .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker push mbialon/concourse-docker-manifest-resource
